ory/x

sqlcon/connector_test.go

• Cleans up duplicated tests cases (_see first commit diff_)
• Adds test coverage for the `WithOmitArgsFromTraceSpans()` option to ensure that the `args` tag is not added to spans when this option has been set. (_second commit_)
_Review: @aeneasr_

sqlcon: add test coverage for WithOmitArgsFromTraceSpans() + DRY up tests

---

go.mod
go.sum

If A-OK, please release as `0.0.33`
👀 @aeneasr

sqlcon: fixes #20 by bumping version of github.com/luna-duclos/instrumentedsql

---

go.mod
httpx/resilient_transport.go
httpx/resilient_transport_test.go

Signed-off-by: aeneasr <aeneas@ory.sh>

httpx: Add resilient transport

---

Makefile
go.mod
go.sum
mod_tools.go
sqlxx/sqlxx.go
sqlxx/sqlxx_test.go

Signed-off-by: aeneasr <aeneas@ory.sh>

sqlxx: Introduce helpers for named insert/updates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
CONTRIBUTING.md

Signed-off-by: aeneasr <aeneas@ory.sh>
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.

docs: Updates issue and pull request templates

---

tracing/tracer.go

https://github.com/ory/hydra/pull/1456
Add a propagation string to the JagerConfig struct.

Add Propagation config

---

tracing/tracer.go

Some changes were made to the tracer in Hydra, but that is no longer being used. Copying those changes over.
• Allows for the standard Jaeger ENV vars to be used in addition to the ORY ones.
• Allows for the b3 header propagation which is used by istio

Copy Tracer from Hydra

---

.circleci/config.yml
Makefile
dbal/connect.go
dbal/migrate.go
dbal/migratest/helper.go
go.mod
go.sum
httpx/resilient_transport.go
sqlcon/connector.go
sqlcon/connector_test.go
sqlcon/dockertest/test_helper.go
sqlcon/message.go
urlx/join.go

Improbe DBAL package

---

dbal/connect.go
sqlcon/connector.go

sqlcon: Add helper for driver name

---

jsonschemax/keys.go

jsonschemax: fix copy paste error

---

jsonschemax/keys.go
jsonschemax/keys_test.go

jsonschemax: add more information to paths

---

viperx/viper.go

viperx: Return logger in InitializeConfig

---

sqlxx/types_slices.go

feat(sqlxx): Add SQL helper types

---

metricsx/middleware.go

feat(metricsx): add close function

---

sqlcon/error.go

- https://github.com/ory/hydra/issues/1719
- https://github.com/ory/hydra/issues/1735 
Add new error handling for the serialization error returned by postgreSQL when using the `REPEATABLE READ` isolation level. This error is returned when an UPDATE/DELETE (TXN2) statement was queued behind another UPDATE/DELETE (TXN1) statement on the same row. Once TXN1 completes and commits, TXN2 will fail to ensure consistency.
- postgreSQL error code appendix: https://www.postgresql.org/docs/9.6/errcodes-appendix.html
- error code: 40001
This error will be consumed by https://github.com/ory/hydra/pull/1766 so it can then return a `fosite. ErrSerializationFailure` which will then be [consumed by `fosite` to render an appropriate RFC 6749 error](https://github.com/ory/fosite/pull/402).
vulnerability, I …

new: add support to sqlcon to handle postgreSQL serialization_failure error

---

go.mod
go.sum
viperx/bind_env_test.go

chore: bump viper to support string arrays as csv

---

metricsx/middleware.go
sqlxx/types.go

feat(sqlxx): add nullable json rawmessage

---

go.mod
go.sum
sqlcon/dockertest/test_helper.go

feat: add pop connection providers to dockertest

---

sqlxx/types.go

fix: use NULL value if json rawmessage is null

---

popx/test_migrator.go

transferred from [hydra/persistence/sql/migratest/helpers.go](https://github.com/ory/hydra/blob/master/persistence/sql/migratest/helpers.go)

feat: add the pop test migrator

---

cmdx/user_input.go
cmdx/user_input_test.go

feat(cmdx): add AskForConfirmation

---

sqlxx/scanner_json.go
sqlxx/scanner_json_test.go

also a `RawJSON` type is added

feat: added kratos' db json scanner functions

---

go.mod
go.sum
viperx/watch_and_validate_viper_test.go

See https://github.com/fsnotify/fsnotify/issues/340

Resolve test issues on macOS

---

go.mod
go.sum

chore: improve dependency cycles

---

popx/test_migrator.go

fix: panic caused by empty migration file

---

sqlcon/dockertest/test_helper.go
tracing/tracer_test.go

feat: add more dockertest helpers

---

sqlcon/error.go

fix: use type switch and support pgconn

---

reqlog/middleware.go
reqlog/middleware_test.go

refactor: remove artificial request_id

---

watcherx/definitions.go
watcherx/event.go
watcherx/file.go
watcherx/file_test.go
watcherx/integrationtest/.dockerignore
watcherx/integrationtest/.gitignore
watcherx/integrationtest/Dockerfile
watcherx/integrationtest/Makefile
watcherx/integrationtest/README.md
watcherx/integrationtest/configmap.yml
watcherx/integrationtest/event_logger.yml
watcherx/integrationtest/eventlog_snapshot
watcherx/integrationtest/main.go
watcherx/integrationtest/run.sh
watcherx/test_helpers.go

The FileWatcher is a kubernetes config map and macos tmp compatible file watcher.
Further we will add more watchers to watch websockets/...

feat: add watcherx/FileWatcher

---

logrusx/logrus.go
logrusx/logrus_test.go

fix(logrusx): prettify on json_pretty only

---

pagination/header_test.go

fix: improve pagination tests

---

clidoc/generate.go

feat: add clidoc helpers

---

clidoc/generate.go

fix(clidoc): improve link generator

---

decoderx/http_test.go

test(decoderx): ensure that payloads are set on errors as well

---

pagination/header.go
pagination/header_test.go

See https://github.com/ory/hydra/issues/1666
the changes.

feat: add x-total-count to pagination headers

---

decoderx/http.go
decoderx/http_test.go

refactor: improve decoderx wording for parse errors

---

decoderx/http.go
decoderx/http_test.go
go.mod
go.sum

feat(decoderx): add ability to format json as form payloads

---

decoderx/http.go

feat(decoderx): add HTTPDecoderAllowedMethods

---

sqlxx/types.go
sqlxx/types_test.go

fix(sqlxx): improve nulltime json unmarshal

---

resilience/retry.go
resilience/retry_test.go

feat: resilience.Retry log error while failing

---

go.mod
go.sum
tracing/tracer.go

https://github.com/ory/hydra/issues/1957
Add DataDog Tracer support
the changes.

feat: Add DataDog support

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/closed_references.yml
.github/workflows/labels.yml
.github/workflows/stale.yml
.reference-ignore
CONTRIBUTING.md
SECURITY.md

Updated repository templates to https://github.com/ory/meta/commit/7900d6c75a8a6e5f583591d5110eacacda1ef286.

chore: update repository template to 7900d6c7

---

go.mod
go.sum

chore: bump datadog to v1.27.0

---

cmdx/helper.go
cmdx/printing.go

contributes to https://github.com/ory/hydra/issues/2124
the changes.

feat: add clihelpers from kratos

---

dbal/migrate_files.go
go_mod_indirect_pins.go
sqlcon/parse_opts.go
sqlcon/parse_opts_test.go

fix: add parseTime=true as default for mysql

---

cmdx/helper.go

Moved from https://github.com/ory/kratos/blob/6ccffa8a1cc5b9fd33435187720257bb66323546/cmd/identities/helpers.go#L79-L105

feat: add cobra test utils

---

go.mod
go.sum
ioutilx/pkger.go
pkgerx/pkger.go

Add pkger and ioutil helpers

---

urlx/parse.go

fix: revert urlx.ParseOrPanic

---

jsonnetx/format.go
jsonnetx/lint.go
jsonnetx/root.go

fix: update package name

---

flagx/flagx.go

feat: add flagx getters for unsigned int types

---

go.mod
go.sum
jsonnetx/format.go
jsonnetx/lint.go
jsonnetx/root.go
pkgerx/pkger.go

fix: update jsonnet format and lint

---

errorsx/errors.go
errorsx/errors_test.go

feat(errorx): add withstack helper

---

watcherx/definitions.go
watcherx/directory.go
watcherx/directory_test.go
watcherx/file.go
watcherx/file_test.go
watcherx/websocket_client.go
watcherx/websocket_server.go
watcherx/websocket_test.go

When triggering a reload on the watcher, it returns a channel that sends the number of events that where dispatched.
This way the requester can wait on all the events to be processed and can tell when this is done even when using buffered channels.

feat(watcherx): notify dispatcher when load trigger is done

---

configx/koanf_confmap.go
configx/koanf_test.go
configx/options.go
configx/provider.go
configx/provider_test.go
flagx/flagx.go
jsonx/helpers.go

the changes.
works.
appropriate).

refactor(configx): improve instantiation factory

---

cmdx/printing.go

BREAKING: this renames some exported types and functions to have more descriptive names. Functionally nothing changed.

feat: add non-table printing capabilities

---

configx/context.go
configx/options.go
sqlcon/dockertest/test_helper.go

the changes.
works.
appropriate).

Improve several APIs and bump dockertest CRDB

---

clidoc/generate.go

the changes.
works.
appropriate).

fix(clidoc): do not process invalid json

---

configx/options.go
configx/provider.go
configx/provider_test.go
go.mod
go.sum

the changes.
works.
appropriate).

feat(configx): add ByteSizeF getter to provider

---

healthx/openapi/patch.yaml

the changes.
works.
appropriate).

feat: add healthx/openapi schema patch

---

cmdx/printing.go
cmdx/printing_test.go

the changes.
works.
appropriate).

feat(cmdx): allow customizing quiet (ID) printing

---

configx/provider.go
watcherx/definitions.go

the changes.
works.
appropriate).

Add documentation

---

configx/options.go
configx/provider.go
configx/provider_watch_test.go
configx/stub/watch/config.schema.json
watcherx/file.go

the changes.
works.
appropriate).

Resolve fsnotify and context leaks

---

configx/provider.go

the changes.
works.
appropriate).

fix: do not register paths twice

---

configx/options.go
configx/provider.go

the changes.
works.
appropriate).

feat(configx): add support for overriding base values

---

go.mod
go.sum
logrusx/logrus.go
logrusx/logrus_test.go

the changes.
works.
appropriate).

feat: Add GELF logrus formatter

---

sqlcon/dockertest/test_helper.go

the changes.
works.
appropriate).

fix: bump crdb to 20.2.5

---

popx/migrator.go

the changes.
works.
appropriate).

fix: use rebind for queries

---

popx/migrator.go
popx/test_migrator.go

the changes.
works.
appropriate).

Fix test migrator

---

logrusx/logrus.go
popx/migration_box.go
popx/migrator.go
popx/migrator_test.go
popx/span.go
popx/test_migrator.go

the changes.
works.
appropriate).

feat(migrator): support tracing and timeouts

---

popx/migrator.go

the changes.
works.
appropriate).

fix(popx): use x tracer

---

popx/migrator.go

the changes.
works.
appropriate).

fix(migrator): expose migration timeout

---

healthx/handler.go
healthx/handler_test.go

the changes.
works.
appropriate).

feat(healthx): add context

---

logrusx/helper.go

https://github.com/ory/keto/issues/454
Just ignore the SQL level

fix(logrusx): ignore pop SQL logs

---

assertx/assertx.go
assertx/assertx_test.go

the changes.
works.
appropriate).

feat(assertx): add equal json except

---

go.mod
go.sum
jwksx/generator.go
jwksx/generator_test.go

the changes.
works.
appropriate).

chore: move to go-jose v3

---

popx/migrator.go

the changes.
works.
appropriate).

fix: filter duplicate migrations

---

popx/consts.go

the changes.
works.
appropriate).

fix: add better in memory dsn to popx

---

dbal/dsn.go
httpx/resilient_client.go

the changes.
works.
appropriate).

Resolve SQLite and resilient client issues

---

assertx/assertx.go
decoderx/http.go
decoderx/http_test.go
go.mod
httpx/resilient_client.go

the changes.
works.
appropriate).

Resolve library issues

---

dbal/dsn_test.go
modx/version.go
modx/version_test.go

the changes.
works.
appropriate).

feat(modx): helper to find version in dependencies

---

healthx/handler.go
healthx/handler_test.go

the changes.
works.
appropriate).

fix(healthx): separate version and health routes

---

decoderx/http.go
decoderx/http_test.go

the changes.
works.
appropriate).

feat(decoderx): support decoding GET requests

---

errorsx/errors.go

https://github.com/ory/fosite/issues/577
the changes.
works.
appropriate).
Let me know your thoughts on whether and how I should approach writing a test for this fix.

Confirm existing stacktrace is not empty

---

cmdx/printing.go
cmdx/printing_test.go
go.mod
go.sum

closes (after bumping ory/x) https://github.com/ory/keto/issues/553
Accidentally I also comited the fix for #325, therefore closes #325

fix(cmdx): JSON print nil

---

go.mod
go.sum

the changes.
works.
appropriate).

chore: bump vulnerable dependencies

---

configx/provider_watch_test.go

the changes.
works.
appropriate).

test: resolve flakes

---

clidoc/generate.go
clidoc/generate_test.go
clidoc/testdata/docs/sidebar.json

the changes.
works.
appropriate).

fix: clidoc for new sidebar

---

clidoc/generate.go
configx/permission_test.go
configx/provider.go
configx/provider_watch_test.go
migratest/refresh.go
migratest/run.go
migratest/strict.go

the changes.
works.
appropriate).

feat(migratest): add migration helpers

---

go.mod
go.sum
popx/transaction.go
popx/transaction_test.go

the changes.
works.
appropriate).

feat(popx): add retry_serializable for crdb

---

decoderx/http.go
decoderx/http_test.go

the changes.
works.
appropriate).

fix(decoderx): support json and form encoding at once

---

configx/provider_watch_test.go
decoderx/http.go

the changes.
works.
appropriate).

fix(decoderx): improve form type detection

---

sqlxx/types.go
sqlxx/types_test.go

fix: avoid stack overflow in *NullString.UnmarshalJSON

---

popx/transaction_test.go

the changes.
works.
appropriate).

test: skip crdb tests on windows

---

popx/migrator.go

the changes.
works.
appropriate).

fix(popx): improve migrator retryability

---

go.mod
prometheusx/handler.go
prometheusx/handler_test.go
prometheusx/metrics.go
prometheusx/middleware.go
prometheusx/middleware_test.go

Moving Prometheus HTTP handler to X. Discussed here https://github.com/ory/hydra/pull/2503#issuecomment-829868412
the changes.
works.
- [] I have added necessary documentation within the code base (if
appropriate).

feat: Prometheusx

---

assertx/assertx.go
prometheusx/handler_test.go
prometheusx/middleware.go
prometheusx/middleware_test.go

the changes.
works.
appropriate).

fix(assertx): ignore newlines

---

sqlxx/types.go

the changes.
works.
appropriate).

docs: add swagger model name

---

prometheusx/handler.go

since this also is used in the Kratos documentation, I thought its good to remove the specific project reference. 
There is also an error with the headline in the reference docs, it should be a `description` not a `summary` I think. 
https://www.ory.sh/kratos/docs/reference/api#get-snapshot-metrics-from-the-hydra-service-if-youre-using-k8s-you-can-then-add-annotations-to
but I am not sure how to change it here.
the changes.
works.
appropriate).

fix: prometheus docs

---

.github/workflows/test.yml

the changes.
works.
appropriate).

ci: pre-download cockroach

---

go.mod
go.sum
watcherx/changefeed.go
watcherx/changefeed_test.go

the changes.
works.
appropriate).

feat(watcherx): support dynamic cursor for changefeed

---

Makefile
watcherx/changefeed.go
watcherx/changefeed_test.go

the changes.
works.
appropriate).

feat(watcherx): return row error if one occurs

---

.github/workflows/test.yml
cmdx/helper.go
go.mod
watcherx/changefeed.go
watcherx/changefeed_test.go

De-flake Keto tests.
Add more helpers to cmdx

feat(cmdx): add more helpers

---

prometheusx/metrics.go

the changes.
works.
appropriate).

fix: do not panic on prometheus duplicate register

---

configx/provider.go

Got some race failures in Keto when running `go test -race`.
Add locks to places where koanf is accessed and written to.

fix(configx): more locks to prevent race conditions

---

prometheusx/handler.go

the changes.
works.
appropriate).

fix: move prometheus to metadata tag

---

castx/castx.go
castx/castx_test.go

related to https://github.com/ory/hydra/issues/2609

fix(castx): use csv parsing for string slices

---

logrusx/helper.go

the changes.
works.
appropriate).

fix: include all headers in log call

---

logrusx/helper.go
reqlog/middleware.go
reqlog/middleware_test.go

the changes.
works.
appropriate).

feat(logrus): include response headers in logs

---

watcherx/changefeed.go

the changes.
works.
appropriate).

fix: remove printf

---

configx/provider_test.go
go.mod
go.sum

in order to solve ory/hydra#2651
* ory/hydra#2651
the changes.
works.
appropriate).

chore: update koanf to v1.2.2

---

Makefile
go.mod
go_mod_indirect_pins.go
migratest/refresh.go
migratest/strict.go
sqlcon/error.go
sqlcon/error_nosqlite.go
sqlcon/error_sqlite.go
urlx/path.go
urlx/path_windows.go

Need to detect "no such table" error.
the changes.
works.
appropriate).

feat(sqlcon): handle ErrNoSuchTable

---

configx/provider.go

the changes.
works.
appropriate).

feat: expose skip validation

---

errorsx/errors.go

the changes.
works.
appropriate).

feat: add ider for errorsx

---

metricsx/middleware.go

the changes.
works.
appropriate).

feat: gRPC telemetry interceptors

---

sqlcon/error_sqlite.go

The sqlite errors were not handled correctly
the changes.
works.
appropriate).

fix: sqlite error handle

---

watcherx/changefeed.go
watcherx/changefeed_test.go

Previously, `CANCEL QUERY` was executed incorrectly. Instead, the underlying connection should be closed!
the changes.
works.
appropriate).

fix(watcherx): close db connection

---

pagination/items.go
pagination/items_test.go
pagination/pagepagination/pagination.go
pagination/pagepagination/pagination_test.go
proxy/proxy_full_test.go

the changes.
works.
appropriate).

feat: add pagination

---

pagination/pagepagination/pagination.go
pagination/pagepagination/pagination_test.go

the changes.
works.
appropriate).

fix: add x-total-count to pagination headers

---

metricsx/middleware.go

Closes https://github.com/ory/k8s/pull/375
Closes https://github.com/ory/kratos/issues/1959
the changes.
works.
appropriate).

fix: several fall backs for SQA_OPT_OUT

---

metricsx/middleware.go

See https://github.com/ory/x/pull/430
the changes.
works.
appropriate).

fix: add fall back for SQA-OPT-OUT

---

sqlxx/types.go
sqlxx/types_test.go

fyi @mitar
the changes.
works.
appropriate).

fix: escape splitx

---

sqlxx/types.go
sqlxx/types_test.go

the changes.
works.
appropriate).

feat(sqlxx): add nullbull

---

sqlxx/types.go
sqlxx/types_test.go

the changes.
works.
appropriate).

feat(sqlxx): new string slice helper

---

sqlxx/types.go

the changes.
works.
appropriate).

fix: improve NullBool SQL compatibility

---

sqlxx/types.go
sqlxx/types_test.go

the changes.
works.
appropriate).

fix: add json helper for duration

---

sqlxx/types.go
sqlxx/types_test.go

the changes.
works.
appropriate).

fix: gracefull handle NULLs in arrays

---

osx/file.go
osx/file_test.go
osx/stub/text.txt

the changes.
works.
appropriate).

feat: add base64,https,file fileloader

---

osx/file.go
osx/file_test.go

As requested @zepatrik 
the changes.
works.
appropriate).

feat(osx): add restricted file loader

---

osx/file.go
osx/file_test.go

the changes.
works.
appropriate).

fix(osx): correct enabled options

---

sqlcon/error.go

the changes.
works.
appropriate).

fix(sqlcon): unwrap errors

---

configx/schema_path_cache.go
jsonschemax/README.md
jsonschemax/keys.go
jsonschemax/keys_test.go

the changes.
works.
appropriate).

fix(jsonschemax): expose array func explicitly

---

go.mod
go.sum

the changes.
works.
appropriate).

chore: bump koanf

---

logrusx/helper.go
logrusx/logrus_test.go

the changes.
works.
appropriate).

fix(logrusx): emit stack traces on debug

---

configx/koanf_full_merge.go
configx/koanf_schema_defaults.go
configx/koanf_schema_defaults_test.go
httpx/private_ip_validator.go
httpx/private_ip_validator_test.go
httpx/resilient_client.go
httpx/resilient_client_test.go

See https://github.com/ory-corp/cloud/issues/1720
the changes.
works.
appropriate).

feat(httpx): add option to client to disable private IPs

---

fetcher/fetcher.go
fetcher/fetcher_test.go

the changes.
works.
appropriate).

fix(fetcher): do not modify the withclient

---

sqlcon/error.go
sqlcon/error_sqlite.go

the changes.
works.
appropriate).

fix(sqlcon): incorrect error wrapping

---

clidoc/generate.go

the changes.
works.
appropriate).

fix: no assumptions about docs structure

---

go.mod
go.sum

the changes.
works.
appropriate).

chore: cdrb 2.2.7

---

go.mod
go.sum
jsonx/patch.go
jsonx/patch_test.go
proxy/proxy_full_test.go
proxy/rewrites.go

the changes.
works.
appropriate).

feat(jsonx): add json-patch

---

.github/workflows/test.yml
sqlcon/dockertest/cockroach.go
sqlcon/dockertest/test_helper.go

the changes.
works.
appropriate).

fix: allow all hosts to connect

---

healthx/handler.go
prometheusx/handler.go

the changes.
works.
appropriate).

Improve httprouter interoperability

---

osx/file.go
osx/file_test.go

the changes.
works.
appropriate).

feat(osx): resilient base64 loader

---

dbal/dsn.go

the changes.
works.
appropriate).

feat(dbal): add unique SQLite helper

---

serverx/404.go
serverx/404.html
serverx/404.json
serverx/404_test.go

See https://github.com/ory/hydra/issues/3064
the changes.
works.
appropriate).

fix: properly handle 404 route

---

go.sum
proxy/proxy.go
proxy/proxy_full_test.go

Add option to add CORS options to the proxy. This will allow the proxy to add the proper cors headers to requests that require them.
the changes.
works.
appropriate).

feat: allow cors on proxy

---

dbal/dsn.go
otelx/otel.go
otelx/otel_test.go

the changes.
works.
appropriate).

fix: implement better SQLite temp database helper

---

tracing/config.go
tracing/config.schema.json
tracing/datadog.go
tracing/http_client.go
tracing/http_client_test.go
tracing/middleware.go
tracing/middleware_test.go
tracing/traced_bcrypt.go
tracing/traced_bcrypt_test.go
tracing/tracer.go
tracing/tracer_test.go

feat: re-add tracing package

---

cloudx/handler.go

Dialog is a variant of dialogue, used primarily in American English in computing contexts.
the changes.
works.
appropriate).

chore: fix typo

---

logrusx/logrus.go

Part of https://github.com/ory/oathkeeper/issues/890
the changes.
works.
appropriate).

fix(logrusx): Log 4xx error as warning level

---

cloudx/cmd_auth_test.go
cloudx/handler.go
cloudx/handler_test.go
dbal/dsn.go

the changes.
works.
appropriate).

fix: force user to relogin on session expiration closes #2342

---

cloudx/handler.go

the changes.
works.
appropriate).

fix: read body only when response exists

---

configx/koanf_test.go
configx/schema_cache.go

the changes.
works.
appropriate).

fix(configx): improve benchmarking

---

otelx/otel.go

the changes.
works.
appropriate).

fix(otelx): add noop tracer when none is configured

---

clidoc/md_docs.go
clidoc/testdata/root-child1-subChild1.md
clidoc/testdata/root-child1.md
clidoc/testdata/root-child2.md
clidoc/testdata/root.md
contextx/config.go
contextx/config_test.go
contextx/tree.go
contextx/tree_test.go
tracing/traced_bcrypt.go
tracing/traced_bcrypt_test.go

the changes.
works.
appropriate).

fix: resolve various issues

---

.gitignore
popx/migration_box.go
popx/migration_box_gomigration_test.go
popx/migration_box_template_test.go
popx/migration_box_testdata_test.go
popx/stub/migrations/testdata/20220513_testdata.sql
popx/stub/migrations/testdata_migrations/20220513_create_table.up.sql

This PR adds `WithTestdata` to the migrator and was extracted from https://github.com/ory/keto/blob/feat/uuid-mapping/internal/persistence/sql/migrations/migratest/migration_test.go#L34.
the changes.
works.
appropriate).

Migration: WithTestdata

---

watcherx/changefeed.go

the changes.
works.
appropriate).

feat(watcherx): changefeed resolved workaround

---

popx/migration_box_testdata_test.go

This PR adds more tests to check that down migrations are properly found.

test: ensure that down migrations are considered

---

servicelocator/options.go
servicelocator/options_test.go

the changes.
works.
appropriate).

feat: implement servicelocator

---

contextx/static.go

the changes.
works.
appropriate).

chore: remove empty file

---

sqlcon/dockertest/test_helper.go

the changes.
works.
appropriate).

fix: expose ConnectPop

---

go.mod
go.sum
popx/migration_box.go
popx/migration_box_testdata_test.go

the changes.
works.
appropriate).

fix: use correct name

---

go.mod
go.sum
httpx/wait_for.go
servicelocator/options.go
servicelocator/options_test.go
sjsonx/set.go
sjsonx/set_test.go

the changes.
works.
appropriate).

feat: add helpers

---

httpx/transports.go

the changes.
works.
appropriate).

feat(httpx): add custom tranpsorters

---

httpx/transports.go

the changes.
works.
appropriate).

feat(httpx): add WrapRoundTripperWithHost

---

httpx/wait_for.go

the changes.
works.
appropriate).

feat(httpx): add WaitForEndpointWithClient

---

testingx/helpers.go

the changes.
works.
appropriate).

feat(testingx): add testing helper utilities

---

josex/public.go
testingx/helpers.go

the changes.
works.
appropriate).

feat(josex): add ToPublicKey

---

httprouterx/nocache.go
httprouterx/redir_test.go
httprouterx/router.go
httprouterx/router_test.go
testingx/helpers.go

the changes.
works.
appropriate).

feat(httprouterx): add helpers for admin routes

---

uuidx/uuid.go

the changes.
works.
appropriate).

feat(uuidx): new package

---

go.mod
go.sum

We are using the latest version of [github.com/ory/x@v0.0.415] which internally uses the rs/cors library and the version is [github.com/rs/cors@v1.8.0] in go.mod
This has introduced snyk vulnerability HTTP Response Splitting with the following path:
github.com/ory/x@v0.0.415 › github.com/rs/cors@v1.8.0 › github.com/gin-gonic/gin@v1.5.0
Snyk issue link: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736
In order to solve this issue I have upgraded rs/cors to latest version.
the changes.
works.
appropriate).

fix: update rs/cors to latest version

---

httpx/private_ip_validator.go
httpx/private_ip_validator_test.go
tracing/traced_pkdbf2.go

vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.

feat(httpx): make ip range error identifiable

---

hashersx/hasher_bcrypt.go
hashersx/hasher_test.go
hashersx/hashers_perf_test.go
hashersx/mocks_argon2_test.go
hashersx/mocks_bcrypt_test.go
hashersx/mocks_pkdbf2_test.go

vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.

test(hashersx): add pkdbf2 perf test

---

clidoc/generate_test.go
otelx/otel_test.go
sjsonx/set_test.go
watcherx/changefeed.go
watcherx/changefeed_test.go

Cockroach might send change events multiple times, so we need
to deduplicate them.
the changes.
works.
appropriate).

fix: deduplicate changefeed events

---

hasherx/mocks_argon2_test.go
hasherx/mocks_bcrypt_test.go
hasherx/mocks_pkdbf2_test.go
popx/migration_box.go
popx/migration_box_test.go

See https://github.com/ory/hydra/issues/3149

fix: do not execute empty migrations with comments

---

cmdx/output.go
sjsonx/set_test.go

feat: add ider output to cmdx

---

.golangci.yml
cmdx/args.go
cmdx/pagination.go
cmdx/pagination_test.go
go.mod
go.sum

feat(cmdx): add pagination helpers

---

hasherx/hashers_perf_test.go

test: report per hash time

---

pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_next_and_last,_but_not_previous_or_first_if_at_the_beginning.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_only_first_if_the_limits_provided_exceeds_the_number_of_clients_found.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_and_last_if_in_the_middle.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_but_not_last_if_in_the_middle_and_no_total_was_provided.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous_and_first_but_not_next_or_last_if_at_the_end.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Header_should_default_limit_to_1_no_limit_was_provided.json
pagination/tokenpagination/pagination.go
pagination/tokenpagination/pagination_test.go

@grantzvolsky @zepatrik @hperl @Benehiko 
This PR adds a common pagination handler based on what @zepatrik introduced in Ory Keto. I suggest to start using this pagination handler across the board as it will allow us for efficient pagination at scale.
PTAL and open an issue or PR if you have suggestions

feat(pagination): add keto pagination handler using encoded tokens

---

dbal/canonicalize.go

Closes https://github.com/ory/hydra/issues/3152

feat: recognize postgresql alias

---

cmdx/http.go

feat(cmdx): add helpers for instantiating HTTP clients with common flags

---

httprouterx/nocache.go
httprouterx/redir_test.go
httprouterx/router.go
httprouterx/router_test.go

feat(httprouterx): refactor helpers

---

sqlxx/types.go
sqlxx/types_test.go

feat(sqlxx): add NullInt64

---

openapix/pagination.go

fix(openapix): use distinct name for pagination headers

---

healthx/doc.go
healthx/handler.go
healthx/handler_test.go

fix: properly expose errors in health checker

---

popx/migrator.go

fix: report original error in migrator

---

ipx/ip_validator.go
ipx/ip_validator_test.go

feat(ipx): add validators for localhost

---

sqlcon/dockertest/test_helper.go

feat: introduce more contorl over versions

---

popx/test_migrator.go

fyi @zepatrik @hperl please ensure to split DDL and DSL statements into different files. This transaction workaround was quite messy and caused several flaky tests in Ory Kratos.
I don't think we have mixed DDL/DSL statements anywhere anymore. If we do, the migration tests will fail and it will be related to this PR.

fix: remove messy crdb transaction workaround

---

httpx/url.go
httpx/url_test.go

feat: add helper for resolving urls from incoming http requsets

---

httpx/url_test.go
proxy/proxy.go

feat(proxy): use custom error handler which does not print context.Canceled errors

---

requirex/time.go
requirex/time_test.go

feat(requirex): add equality check for time and durations

---

popx/migrator.go

fix(popx): faster migration checks

---

.github/workflows/test.yml
servicelocatorx/options.go
servicelocatorx/options_test.go

feat: improved servicelocator

---

tlsx/cert.go
tlsx/cert_test.go

This PR adds support for generating certificates from Ed25519. It is usually as fast as the fastest NIST curve (P256). It is supported in TLS 1.3.

feat: add support for Ed25519

---

otelx/config.schema.json

Related to [this thread in the chat](https://ory-community.slack.com/archives/C02PSRUGUAV/p1660648129929739)
I've seen it's possible to use an [agnostic opentelemetry provider](https://github.com/ory/x/blob/v0.0.392/otelx/otel.go#L55-L62), but the `tracing.provider` enums needs to support `otel` too, otherwise it gets rejected by the application as only zipkin and jaeger are valid values in the schema.
I am unsure if configuration values should be tested in anyway, please advice and I'll add the config.

make it possible to configure OTEL agnostic providers

---

contextx/contextual.go

feat: add noop contextualizer

---

httpx/private_ip_validator.go
httpx/resilient_client.go
httpx/resilient_client_test.go

feat(httpx): skip certain URLs in internal IP exceptions

---

README.md
pagination/README.md

Tests are running on GitHub Actions now.

ci: update badge from CircleCI to GitHub Actions

---

httpx/client_info_test.go
proxy/rewrites.go
proxy/rewrites_test.go
stringsx/ptr_test.go

feat(proxy): rewrite cookie secure and samesite attributes

---

proxy/rewrites_test.go

test: adjust regression

---

prometheusx/middleware.go
prometheusx/middleware_test.go

This PR fixes the issue is that the prometheusx.MetricsManager is not safe for concurrent use with regards to ServeHTTP and RegisterRouter . In Keto we launch multiple HTTP servers for the read, write and metrics routes, which concurrently call first RegisterRouter  and then ServeHTTP.

fix: race condition in prometheusx

---

stringsx/truncate.go
stringsx/truncate_test.go

- Introduce func to return string after truncation by length specified

feat: add trunc func

---

pagination/pagepagination/pagination.go
pagination/tokenpagination/pagination.go

feat: export pagination headers

---

pagination/pagepagination/pagination.go
pagination/tokenpagination/pagination.go

refactor: rename structs

---

pagination/pagepagination/pagination.go
pagination/tokenpagination/pagination.go

feat: add more annotations for pagination

---

sqlcon/error.go
sqlcon/error_sqlite.go

feat: add handling for table locked errors

---

pagination/tokenpagination/pagination.go

docs: improve tokenpagination headers

---

httpx/transports.go

feat: add roundtrip wrapper for header

---

httpx/private_ip_validator.go

feat: ignore query params on comparison

---

logrusx/logrus.go

feat: bump log precision for json format, ISSUE-617

---

cmdx/printing.go
cmdx/printing_test.go

This PR adds a flag `--format=jsonpath=foo.bar.baz` to filter the JSON response.

feat: add jsonpath format option

---

pagination/keysetpagination/paginator.go
pagination/keysetpagination/paginator_test.go

Paginate based on Dialect check for mysql

fix: paginate escape column name

---

Makefile
configx/koanf_file.go
configx/koanf_file_test.go
configx/koanf_memory.go
configx/koanf_test.go
configx/permission_test.go
configx/provider.go
configx/provider_test.go
configx/provider_watch_test.go
logrusx/helper.go
otelx/jaeger.go
otelx/middleware.go
otelx/middleware_test.go
otelx/otel.go
otelx/otel_test.go
otelx/otlp.go
otelx/semconv/events.go
otelx/zipkin.go
reqlog/middleware.go

Ref https://github.com/ory-corp/cloud/issues/3008
Prep work for more changes in kratos/cloud.
Threw in a couple of lint issues my IDE kept bringing up.

feat: x/otelx prep work for tracing enhancements

---

pagination/header.go
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_next_and_last,_but_not_previous_or_first_if_at_the_beginning.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_only_first_if_the_limits_provided_exceeds_the_number_of_clients_found.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_and_last_if_in_the_middle.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_but_not_last_if_in_the_middle_and_no_total_was_provided.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous_and_first_but_not_next_or_last_if_at_the_end.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Header_should_default_limit_to_1_no_limit_was_provided.json
pagination/migrationpagination/header.go
pagination/migrationpagination/pagination.go
pagination/migrationpagination/pagination_test.go
pagination/pagepagination/header.go
pagination/pagepagination/pagination.go
pagination/tokenpagination/header.go
pagination/tokenpagination/pagination.go

feat: add helpers for migrating to keyset pagination

---

pagination/keysetpagination/header.go
pagination/keysetpagination/paginator_test.go

The function signature of `keysetpagination.Parse` takes a pointer to a `url.Values`. This is problematic, as most often this param will come from `r.URL.Query()` which does not return a pointer. So a user of that function needs to 
1. assign the return value to a local variable
2. take the pointer to that variable's value and pass it into `keysetpagination.Parse`
This is a bit awkward and could be cleaned up, if we remove the pointer notation (this PR).
`url.Values` is just a type alias to a `map[string][]string` which internally is already a pointer. It's just GoLang's semantics that make `map`s look like values (https://dave.cheney.net/2017/04/30/if-a-map-isnt-a-reference-variable-what-is-it)
BREAKING CHANGES: This PR removes the "pointer" notation from the parameter to …

fix: change keysetpagination.Parse signature to use value

---

httpx/private_ip_validator.go
httpx/private_ip_validator_test.go

fix(httpx): url parsing regression in private ip

---

assertx/assertx.go
assertx/assertx_test.go

feat(assertx): add time less than helper

---

pagination/header.go
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_next_and_last,_but_not_previous_or_first_if_at_the_beginning.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_only_first_if_the_limits_provided_exceeds_the_number_of_clients_found.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_and_last_if_in_the_middle.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_but_not_last_if_in_the_middle_and_no_total_was_provided.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Create_previous_and_first_but_not_next_or_last_if_at_the_end.json
pagination/migrationpagination/.snapshots/TestPaginationHeader-Header_should_default_limit_to_1_no_limit_was_provided.json
pagination/migrationpagination/pagination.go
pagination/migrationpagination/pagination_test.go
pagination/pagepagination/pagination.go
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_next_and_last,_but_not_previous_or_first_if_at_the_beginning.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_only_first_if_the_limits_provided_exceeds_the_number_of_clients_found.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_and_last_if_in_the_middle.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous,_next,_first,_but_not_last_if_in_the_middle_and_no_total_was_provided.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Create_previous_and_first_but_not_next_or_last_if_at_the_end.json
pagination/tokenpagination/.snapshots/TestPaginationHeader-Header_should_default_limit_to_1_no_limit_was_provided.json
pagination/tokenpagination/pagination.go
pagination/tokenpagination/pagination_test.go

See https://github.com/ory/hydra/issues/3362

fix: pagination offset

---

httpx/private_ip_validator.go
httpx/private_ip_validator_test.go
httpx/resilient_client.go
httpx/resilient_client_test.go

feat: lighter SSRF migration

---

go.mod
httpx/client_info.go
httpx/client_info_test.go
otelx/semconv/events.go
pagination/keysetpagination/paginator.go
pagination/keysetpagination/paginator_test.go

Ref https://github.com/ory-corp/cloud/issues/3493 https://github.com/ory-corp/cloud/issues/3527
Checkout the commits for details.

feat: event naming+additional attribute + bonus improvement

---

otelx/withspan.go
otelx/withspan_test.go

This simplifies tracing instrumentation and sets the correct span status, enhancing UX in tracing UIs.

feat: add WithSpan helper

---

configx/provider.go
otelx/config.go
otelx/config.schema.json
otelx/config_test.go
otelx/jaeger.go

Added missing configuration for jaeger remote sampler.
Without this configuration, traces are not being sent to Jaeger.
https://github.com/ory/x/issues/655
- [] I have added the necessary documentation within the code base (if appropriate).

refactor: add missing config for jaeger

---

httpx/private_ip_validator.go
httpx/private_ip_validator_test.go
httpx/resilient_client.go
httpx/resilient_client_test.go

revert: lighter SSRF migration (#641)

---

httpx/private_ip_validator.go

fix: update error message

---

go.mod
go.sum
popx/migrator.go

fix: update mysql

---

.github/workflows/test.yml

chore: pin nancy

---

decoderx/http.go
decoderx/http_test.go
decoderx/stub/dynamic-object.json

fix: correctly deal with premarshalled json objects

---

fetcher/fetcher.go
fetcher/fetcher_test.go

This adds a new `Fetcher.FetchContext` method that takes a context that can be used to cancel fetching HTTP(S) content.

feat: cancellable fetcher

---

metricsx/middleware.go
metricsx/middleware_test.go

fix: metricx anonymizePath
fix: Page payload remove extras and added host, tls

fix: metricx anonymizePath

---

otelx/withspan.go
otelx/withspan_test.go

The inspected interfaces are a subset of those used by ory/herodot: https://github.com/ory/herodot/blob/8771415caa5878ce89788835a17b0aefe935a4ce/error_default.go#L375-L414
Here's how this is useful: we often internally have more detail about an error condition than we want to expose over our API. Before this change, we'd only get this message: `An internal server error occurred, please contact the system administrator`. After this change, we get the inside info too:

feat: inspect wrapped errors and add additional info to traces

---

otelx/semconv/context.go
otelx/semconv/context_test.go
otelx/semconv/events.go

feat: add semantic conventions

---

decoderx/http.go

Removed `io/ioutil` and other minor fixes as annotated.
Closes https://github.com/ory-corp/cloud/issues/4298 (once bumped upstream).

fix(decoderx): minor fixes

---

.github/workflows/format.yml
.github/workflows/licenses.yml
.github/workflows/test.yml
proxy/proxy.go

See https://github.com/golang/go/issues/50580

fix(proxy): switch to `httputil.ReverseProxy.Rewrite`

---

otelx/middleware.go
otelx/middleware_test.go

This PR addresses a memory leak issue in the OpenTelemetry tracing middleware.
The existing middleware invokes NewHandler for each incoming request, which results in the allocation of a new oteltracehttp.Handler.
```
func TraceHandler(h http.Handler, opts ...otelhttp.Option) http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
NewHandler(h, r.URL.Path, opts...).ServeHTTP(w, r)
})
}
```
In our setup, this led to an increase of over 300MB per day per Hydra instance in allocated memory. Similar observations have been reported in open-telemetry/opentelemetry-go-contrib#2413.
This PR modifies the middleware to utilize a SpanNameFormatter function instead of passing the path to NewHandler. This preserves the existing functionality while eliminating the memory …

fix(otelx): memory leak in OpenTelemetry tracing middleware

---

go.mod
go.sum
metricsx/middleware.go
modx/version_test.go

SQA metrics V2 using analytics-go v5
All products require minor changes to parameters to enable this

feat: sqa metrics v2

---

jsonx/patch.go
jsonx/patch_test.go

fix: jsonpatch replace

---

otelx/jaeger.go
otelx/otlp.go

Currently, if Ory Oathkeeper is setup with the `otel` tracer and the upstream application is using Jaeger, Oathkeeper doesn't pass along the appropriate headers. This was occurring with Grafana Mimir/Loki/Tempo as the upstream for Oathkeeper since they only support Jaeger, but Oathkeeper wasn not propagating the headers that Jaeger can read. This PR ensures all trace headers are passed around irrespectively of the tracer Oathkeeper is configured with.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204862492310345

fix(otelx): forward all headers

---

go.mod
go.sum
josex/generate.go
josex/public.go
josex/utils.go
jwksx/fetcher.go

chore(deps): update go-jose

---

popx/migrator.go

fix: remove up-to-step event

---

proxy/proxy.go

fix: use incoming TLS to detect originalScheme

---

go.mod
go.sum
httpx/private_ip_validator.go
httpx/resilient_client.go
httpx/resilient_client_test.go

Part of https://github.com/ory-corp/cloud/issues/5038

feat: match exception URLs via globbing

---

configx/provider.go
otelx/config.go
otelx/config.schema.json
otelx/otlp.go

This PR adds `deployment.environment` attribute to OTEL data
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security vulnerability. 

feat: add `deployment.environment` attribute to OTEL data (CORE-2294)

---

configx/provider.go
configx/provider_test.go

It's fast:
```
BenchmarkSet
BenchmarkSet-8                       	    6189	   9197403 ns/op
BenchmarkDirtyPatch
BenchmarkDirtyPatch-8                	  401864	      3057 ns/op
```

feat: add DirtyPatch method

---

pagination/migrationpagination/header.go
pagination/pagepagination/header.go

fix: add missing pagination parameters to migrationpagination package

---

.github/workflows/test.yml
Makefile
sqlcon/parse_opts.go
sqlcon/parse_opts_test.go

feat: force clientFoundRows to true

---

crdbx/staleness.go
crdbx/staleness_test.go

fix: correctly return unset for consistency

---

crdbx/readonly.go

feat: add a read only transaction helper

---

jwksx/fetcher_v2.go

Needed for https://github.com/ory/kratos/pull/3594

feat: add custom JWK parse error type

---

sqlxx/batch/create.go

feat: improve batch create API

---

sqlxx/types.go
sqlxx/types_test.go

feat: add nullable bool defaulting to false

---

snapshotx/snapshot.go

feat: add WithReplacement except opt to snapshot

---

healthx/doc.go
healthx/openapi/patch.yaml

fix: use schemas for health

---

healthx/doc.go

fix: also revert model change in version schema

---

otelx/jaeger.go
otelx/otel_test.go

When tracing, take into account the sampling decision from the parent.
https://opentelemetry.io/docs/languages/go/sampling/

feat(tracing): respect parent sampling configuration

---

otelx/semconv/events.go

feat: add more semconv attributes

---

jsonnetsecure/provider.go

chore(jsonnetx): support TB

---

logrusx/helper.go

feat: add WithSpanFromContext logrus helper

---

popx/loggers.go

feat: add helpers for pop logging

---

cmdx/helper.go

to preserve the call stack properly

chore(cmdx): do not run commands in the background when not needed

---

logrusx/helper.go
logrusx/logrus_test.go

fix: add x-session-token to redacted headers

---

jsonnetsecure/provider.go

fix(jsonnet): add higher timeout for tests

---

otelx/attribute.go
otelx/semconv/events.go

Adds one attribute key for both project and workspace API keys.

feat(otelx): add API key attribute keys

---

otelx/semconv/deprecated.go

See https://github.com/ory-corp/cloud/issues/6930

feat: add depreacted event

---

popx/migrator.go

Reverts part of #816, as we observed `ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn`

revert: removed crdb execute from migrator

---

jsonx/patch.go
jsonx/patch_test.go

fix: ignore casing in ApplyJSONPatch deny list

---

logrusx/helper.go

Fixes https://github.com/ory-corp/cloud/issues/5656

fix: redact query of location header

---

.github/workflows/test.yml
.golangci.yml
Makefile
httpx/content_type.go
httpx/content_type_test.go

Contributes to https://github.com/ory-corp/cloud/issues/7392

fix: content type parsing in httpx

---

randx/strength/go.mod
sqlxx/types.go
sqlxx/types_test.go

feat: add IsZero() to sqlxx types

---

configx/provider.go

This puts OTEL in line with the jaeger config. The motivation for this was the time spent debugging why no traces were being sent from a pod running `oryd/hydra` with our basic config:
tracing:
provider: otel
service_name: ory-hydra
deployment_environment: development
providers:
otlp:
server_url: our-collector:4318
insecure: true

feat(configx): default otel sampling rate to 1

---

jsonx/debug.go
jsonx/debug_test.go

This adds a function `jsonx.Anonymize` to scrub all data from a JSON object while maintaining debuggability.

feat: anonymize JSON data

---

otelx/semconv/deprecated.go
otelx/semconv/warning.go

feat: add warning to events

---

assertx/assertx.go
castx/castx.go
cmdx/args.go
decoderx/http.go
flagx/flagx.go
fsx/merge.go
httpx/content_type.go
httpx/gzip_server.go
httpx/url.go
httpx/wait_for.go
josex/encoding.go
jsonnetx/format.go
jsonnetx/lint.go
jsonnetx/root.go
jsonx/embed.go
jsonx/get.go
jsonx/helpers.go
jwtx/claims.go
logrusx/logrus.go
metricsx/middleware.go
osx/env.go
requirex/time.go
requirex/time_test.go
stringsx/coalesce.go
stringsx/default.go

All changes should be backwards-compatible.

chore: deprecate some code and minor improvements
