ory/x

- go.mod
- go.sum
- sqlcon/connector.go
- sqlcon/connector_test.go
- sqlcon/options.go
This PR adds support for tracing db queries by wrapping the driver with one instrumented w/ the opentracing API. This new ability has been introduced in a backwards compatible manner by following the options pattern: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis
Existing consumers of the `sqlcon` package need not worry if they have no need for distributed tracing - **their code will work as is**.
Consumers of `sqlcon` interested in tracing their db calls (_e.g. Ory Hydra_) can now do something like:
```
options := []sqlcon.Opt{sqlcon.WithDistributedTracing(), sqlcon.WithOmitArgsFromTraceSpans()}
connection, err := sqlcon.NewSQLConnection(url, l, options...)
if err != nil {
return err
}
s.l = l
s.db = connection.GetDatabase()
```
• New dependency has been added as …
> sqlcon: add support for tracing database driver

- go.mod
- go.sum
[Hydra requires the option `AllowOriginRequestFunc`](https://github.com/ory/hydra/blob/master/cmd/server/helper_cors.go#L58) which was added in `v1.6.0`.
Change log between [`v1.5.0` to `v1.6.0`](https://github.com/rs/cors/compare/v1.5.0...v1.6.0)
This is required for bumping Hydra's version of `ory/x` to `v0.0.14` (_for bringing in tracing support for SQL calls_) as it is currently on `v0.0.5`
_Review: @aeneasr_
> Bump version of github.com/rs/cors to v1.6.0

- sqlcon/connector_test.go
- sqlcon/options.go
This will be useful for writing integration tests in Hydra as you cannot register a driver with the same name more than once.
👀 @aeneasr
> sqlcon: expose option for using random driver names when configuring tracing

- profilex/profiling.go
Signed-off-by: Kevin Minehart <kmineh0151@gmail.com>
https://github.com/ory/hydra/issues/1061
`profilex` functions were watching for shutdown signals, causing the file writers to never `Close`.
This change disables watching for shutdown signals in the profile package.
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
I didn't see a very good place to write tests for this type of change. If you have any suggestions, then please let me know. :)
> Don't watch for shutdown signal on profiling

- pagination/header.go
- pagination/header_test.go
Signed-off-by: Kevin Minehart <kmineh0151@gmail.com>
https://github.com/ory/hydra/issues/1047
Add a function to create pagination a "Link" header given an offset and a limit.
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
This is a necessary addition in order to complete the issue in Hydra. I figured this was a good place to add the header functionality, in case any other Ory products might use this same type of pagination.
If it should stay in Hydra …
> add pagination functions for use in ory/hydra

- .circleci/config.yml
- dbal/canonicalize.go
- dbal/connect.go
- dbal/migrate.go
- dbal/migratest/helper.go
- sqlcon/connector.go
- sqlcon/connector_test.go
- sqlcon/dockertest/test_helper.go
- sqlcon/message.go
- sqlcon/migrate.go
- sqlxx/sqlxx.go
- sqlxx/sqlxx_test.go
add support for cockroachdb
This would need to be merged before: https://github.com/ory/hydra/pull/1348
Add support for cockroachdb in x.
> all: add support for cockroachdb

- sqlcon/connector.go
- sqlcon/connector_test.go
If  user name of DB contains"@" char, the sqlcon can't connect to the DB.
The DSN example is as following:
DSN=mysql://sa@test.mysql.database.azure.com:MyPassword@(127.0.0.1:3306)/hydra
This PR do a very simple fix.
> Fix the DB username can't contain "@" character

- sqlcon/connector.go
If dsn starts with "mysql://", the sqlcon will expose username&password unsafety.
Before
```go
// c.DSN is
// mysql://root:root@tcp(localhost:32777)/shield?max_conns=20&max_idle_conns=4
dsn, err := connectionString(c.DSN) 
// dsn is
// root:root@tcp(localhost:32777)/shield?parseTime=true
classifiedDSN := classifyDSN(dsn)
// classifiedDSN is
// root:root@tcp(localhost:32777)/shield?parseTime=true://*:*@tcp(localhost:32777)/shield?parseTime=true
```
After
```go
// c.DSN is
// mysql://root:root@tcp(localhost:32777)/shield?max_conns=20&max_idle_conns=4
dsn, err := connectionString(c.DSN) 
// dsn is
// root:root@tcp(localhost:32777)/shield?parseTime=true
// fulfil classifyDSN()'s format, which must starts with schema://
dsnToClassify := dsn
if driverName == "mysql" {
dsnToClassify = "mysql://" …
```
> fix username&password exposed when dsn's schema is mysql

- go.mod
- go.sum
Resolves #97 
Tried to update go.mod with as few other changes as possible. Not sure if there are breaking changes between `20181127104832` and `v1.1.2`, hopefully tests will catch any regressions.
> Update instrumentedsql to latest version

- viperx/helper.go
- viperx/helper_test.go
- viperx/stub/json/.project-stub-name.json
- viperx/stub/toml/.project-stub-name.toml
- viperx/stub/yaml/.project-stub-name.yaml
- viperx/stub/yml/.project-stub-name.yml
https://github.com/ory/oathkeeper/issues/305
Helper method that uses viper.AllSettings which will do env var replace since viper.GetStringMap does not.
> add helper method to get config with env vars

- httpx/resilient_client.go
https://github.com/ory/oathkeeper/issues/310
Allow timeout to be configurable
> add abiltity to specify timeout when creating client

- jsonschemax/keys.go
- jsonschemax/keys_test.go
https://github.com/ory/kratos/issues/175
The returned Path struct now includes the format and pattern defined by the schema
> jsonschemax: add format and pattern to path

- jsonschemax/keys.go
- jsonschemax/keys_test.go
To enable custom properties in paths we add a the PathEnhancer that allows you to set custom properties on a path.
> feat(jsonschemax): Add PathEnhancer to extensions

- viperx/stub/config.schema.json
- viperx/validate.go
- viperx/validate_test.go
All validation error fields will be present in the output log. Until now only the last error was logged.
Also I changed the key format to not include the index because the order was not deterministic.
> fix(viperx): multiple validation errors

- sqlcon/migrate.go
https://github.com/ory/keto/issues/145
Parse a DSN string manually instead of using `url.Parse` since a DSN string for MySQL is no longer always parsable with `url.Parse` after [this change](https://go-review.googlesource.com/c/go/+/189258/) (Ref: https://github.com/golang/go/issues/33646).
```sh
$ cat <<EOF > main.go
package main
import (
"fmt"
"net/url"
)
func main() {
fmt.Println(url.Parse("mysql://tcp(127.0.0.1:3306)/"))
}
EOF
$ go version
go version go1.14 darwin/amd64
$ go run main.go
<nil> parse "mysql://tcp(127.0.0.1:3306)/": invalid port ":3306)" after host
```
I have only tested this with `keto migrate sql`.
> fix(sqlcon): Parse DSN manually instead of using url.Parse

- metricsx/middleware.go
> fix(metricsx): fall back only when sqa-opt-out errors

- sqlcon/dockertest/test_helper.go
This turned out to be problematic as a test might reuse a container.
Cleanup should be done with `dockertest.KillAllTestDatabases()` instead.
> fix: remove automatic test cleanup

- sqlcon/parse_opts.go
- sqlcon/parse_opts_test.go
ParseConnectionOptions will also return the DSN URI with removed connection options.
> feat(sqlconn): enhance ParseConnectionOptions to return cleaned DSN

- sqlcon/parse_opts.go
- sqlcon/parse_opts_test.go
For now this function only sets the query parameter `multiStatements=true` for mysql.
> feat(sqlcon): add FinalizeDSN

- logrusx/helper.go
Currently, `http_request` is lost when `otel` is add.
like this
```
{"level":"info","msg":"started handling request","otel":{"span_id":"00f067aa0ba902b7","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736"},"span_id":"00f067aa0ba902b7","time":"2020-06-11T09:51:23+09:00","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736"}
{"audience":"application","error":{"message":"invalid_request","reason":"The POST body can not be empty.","status":"Bad Request","status_code":400},"level":"error","msg":"An error occurred","otel":{"span_id":"00f067aa0ba902b7","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736"},"service_name":"","service_version":"","span_id":"00f067aa0ba902b7","time":"2020-06-11T09:51:23+09:00","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736"}
{"http_response":{"status":400,"text_status":"Bad …
```
> fix: Tracing logging with request logging

- logrusx/logrus.go
Rollback log format configuration to `log.format` from `log.formatter` if unintentional. (because I couldn't find this change at CHANGELOG.md)
Environment variable is not changed because it remains `LOG_FORMAT`.
ref #155
the changes.
> fix: Rollback log format configuration

- popx/test_migrator.go
See https://github.com/gobuffalo/pop/issues/567
> fix: resolve escaping issue in popx test migrator

- viperx/stub/yml/.project-stub-name-invalid-path.yml
- viperx/viper.go
- viperx/viper_test.go
This fixes simply trims whitespaces from the configuration file path if one has been specified -c // --config flag. 
This fixes a problem if you try to run e.g. Kratos and specify a custom configuration will with -c // --config flag without specifying each part of the commandline call as a seperate string literal: 
`kratos serve "-c ./myconfig.yml"`
fails with the following error message, although the file exists and the process has sufficient permissions to read the file:
`Unable to open config file. Make sure it exists and the process has sufficient permissions to read it  audience=application error=map[message:open  ./myconfig.yml: no such file or directory] path= ./contrib/quickstart/kratos/email-password/.kratos.yml service_name=kratos service_version=`
This is caused by the handling …
> fix: removing whitespaces in config file path

- watcherx/directory_test.go
- watcherx/file_test.go
I ran the flaky directory watcher test with a count of 10,000 and it passed, guess it is not flaky anymore.
> fix: reduce watcherx test flakyness

- .github/workflows/closed_references.yml
- .github/workflows/stale.yml
- CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/1d3bdaf243c166ab2ed8a6de1c33ca728ff620a3.
> chore: update repository template to 1d3bdaf2

- reqlog/middleware_test.go
The test was failing [here](https://github.com/ory/x/pull/219/checks?check_run_id=1295947127) because the string representation was `10ms`, which the pattern would not allow. On the other hand it would allow `10.0ms`. Runs where e.g. the time would be exactly 11ms would also have failed the test by the way. Using comparison operators ensures that the whole range passes.
> test: remove flakiness in reqlog test

- .github/workflows/windows_test.yml
- urlx/parse.go
- urlx/parse_test.go
- urlx/path.go
- urlx/path_test.go
- urlx/path_windows.go
This code was first created for PR #557 in oathkeeper.
It should probably be in the shared ory/x project instead of there,
so that is why this code is checked in here.
Related Ory person: @zepatrik 
the changes.
See other PR for more details
> fix: Functions to parse URLs and handle URL file paths

- viperx/vars.go
- viperx/vars_test.go
@zepatrik as discussed in Slack
When setting up Kratos with Helm I would like to be able to configure some of the options via env vars rather than the config file because the values will contain sensitive data like client id / client secret.
This change will try to parse the values that come in to `UnmarshalKey` as JSON, and then falling back to the previous behaviour of encoding then decoding. Further comments below.
the changes.
This change will allow me to do something like setting an env var called `SELFSERVICE_METHODS_OIDC` containing a json object that specifies the value of the `oidc` struct. …
> feat(viperx): Add support for parsing config passed through env vars as json

- stringsx/switch_case.go
- stringsx/switch_case_test.go
This will allow the following:
```go
knownExtensions := stringsx.RegisteredCases{}
switch ext := filepath.Ext(fn); ext {
case knownExtensions.AddCase("yaml"), knownExtensions.AddCase("yml"):
case knownExtensions.AddCase("toml"):
case knownExtensions.AddCase("json"):
default:
k.l.Errorf("Namespace file %s has an unknown file extension %s, expected one of %s.", fn, ext, knownExtensions)
}
```
> feat: add simple string switch case recorder

- configx/koanf_file.go
- configx/koanf_file_test.go
- configx/options.go
- configx/provider.go
- configx/provider_watch_test.go
- go.mod
- stringslice/reverse.go
- stringslice/reverse_test.go
This will allow us to do e.g.:
Keto namespaces are defined each in the root config file under `namespaces.[id]`. They can then either be defined together with everything else  in the config file, or live in their own (probably default for most people). When they are in their own file, they will be merged into the overall config under the subkey `namespaces.[id]`.
> feat: allow nested koanf file merging

- stringsx/switch_case.go
- stringsx/switch_case_test.go
Example usage:
```go
knownFormats := stringsx.RegisteredCases{}
switch ext := filepath.Ext(source); ext {
case knownFormats.AddCase("yaml"), knownFormats.AddCase("yml"), knownFormats.AddCase("json"):
parser = yaml.Unmarshal
case knownFormats.AddCase("toml"):
parser = toml.Unmarshal
default:
return nil, knownFormats.ToUnknownCaseErr(ext)
}
```
> feat: add ErrUnknownCase to stringsx.RegisteredCases

- .github/workflows/windows_test.yml
- configx/koanf_file.go
- configx/provider.go
- configx/provider_watch_test.go
- watcherx/definitions.go
- watcherx/directory.go
- watcherx/directory_test.go
- watcherx/event.go
- watcherx/file.go
- watcherx/file_test.go
- watcherx/integrationtest/main.go
- watcherx/websocket_client.go
- watcherx/websocket_server.go
- watcherx/websocket_test.go
In many cases the data have to be retrieved when starting the watcher as well.
This adds a possibility to signal to the watcher that you need it to send the current value as if it changed into the current state.
> feat(watcherx): allow requesting current data

- .circleci/config.yml
- .github/workflows/windows_test.yml
- clidoc/generate.go
- configx/koanf_file_test.go
- configx/options.go
- configx/provider.go
- configx/provider_test.go
- configx/provider_watch_test.go
- httpx/gzip_server.go
- watcherx/event.go
- watcherx/file_test.go
- watcherx/test_helpers.go
- watcherx/websocket_test.go
CI failing all the time
A propagated change is now signaled by a channel instead of a wait group. This results in the test blocking until the change propagates, but subsequent events are ignored. They appeared until now because the cleanup of files and closing of the fsnotify watcher were racy.
> test: fix flaky configx tests

- cmdx/helper.go
- logrusx/helper.go
The two commits are independent and should not be sqashed.
The pop logger allows us to have the pop logs in logrus using
```go
pop.SetLogger(l.PopLogger)
```
The command executor can be used to call a command multiple times with a given context and persistent arguments. E.g.
```go
c := &cmdx.CommandExecuter{
New: cmd.NewRootCmd,
Ctx: ctx,
PersistentArgs: []string{"--config", "path/to/test/config"},
}
```
> feat: logrusx pop logger and context in cmdx

- cmdx/noise_printer.go
- cmdx/noise_printer_test.go
- cmdx/printing.go
This allows us to write better readable code in commands that print. E.g.:
```go
if !flagx.MustGetBool(cmd, FlagQuiet) {
fmt.Fprintf(cmd.ErrOrStderr(), "Increasing memory to get over %s:\n", desiredDuration)
}
```
becomes
```go
loudPrinter := cmdx.NewLoudOutPrinter(cmd)
loudPrinter.Printf("Increasing memory to get over %s:\n", desiredDuration)
```
> feat(cmdx): add conditional printer and noise convenience functions

- cmdx/printing.go
- cmdx/printing_test.go
With #257 the default format for a table printer was changed by mistake to no output.
> fix(cmdx): table printing default should be table

- cmdx/helper.go
- sqlcon/dockertest/test_helper.go
Using `testing.TB` allows to pass either `*testing.T` or `*testing.B`. Using `require.TestingT` will even allow wrapping the original testing struct to allow e.g. concurrent `FailNow()`. We should use the least restricting type possible from now on.
> chore: use interfaces instead of testing types

- CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/bb146082236a7bbb94c3e042951b937aa76d25a4.
> chore: update repository template to bb146082

- cmdx/printing.go
- cmdx/printing_test.go
- pkgerx/migration_box_test.go
An empty table produces no output currently, while it should print the header or JSON representation.
> fix: match printing of empty table to Docker CLI

- .circleci/config.yml
- Makefile
- go.mod
- go.sum
- logrusx/logrus.go
Since https://github.com/ory/x/commit/e11ad97c55f23d97a4e9e1365cc1b5d0e46243b2 the CI was **not running any tests**. By updating the go-acc version, tests are properly running again.
> chore: bump ory/go-acc

- popx/migration_box.go
- popx/migration_info.go
- popx/migration_info_test.go
- popx/migrator.go
- popx/test_migrator.go
This patch makes sure that specific migrations (e.g. 1234_foobar.sqlite.up.sql) override generic migrations (e.g. 1234_foobar.up.sql).
/cc @zepatrik
> fix: handle migration precedence appropriately

- clidoc/generate.go
- clidoc/generate_test.go
- clidoc/testdata/docs/docs/cli/root-child1-subChild1.md
- clidoc/testdata/docs/docs/cli/root-child1.md
- clidoc/testdata/docs/docs/cli/root-child2.md
- clidoc/testdata/docs/docs/cli/root.md
- clidoc/testdata/docs/sidebar.json
Regression of the sidebar spam bug. Looks like this was caused because of a change to the sidebar file format. Added a snapshot test.
> fix(clidoc): sidebar spam

- clidoc/generate.go
the changes.
works.
appropriate).
> fix(clidoc): escape html chars

- .github/auto_assign.yml
Updated repository templates to https://github.com/ory/meta/commit/567c6345b7a1fdf3b48420f74ecd1a536b1f2cd2.
> chore: update repository template to 567c6345

- .github/CODEOWNER
Updated repository templates to https://github.com/ory/meta/commit/c7a2e1f9ac8e52f80278670c47aa6a562872ebc5.
> chore: update repository template to c7a2e1f9

- decoderx/http.go
- decoderx/http_test.go
the changes.
works.
appropriate).
> feat(decoderx): explicit request query checking

- decoderx/http.go
- decoderx/http_test.go
the changes.
works.
appropriate).
> feat(decoderx): support query params in json payloads as well

- configx/provider.go
- tracing/config.go
- tracing/tracer.go
https://github.com/ory/hydra/issues/2447
Make the maxTagValueLength configurable for jaeger
the changes.
works.
appropriate).
The issue [2447](https://github.com/ory/hydra/issues/2447) need another change on ory/hydra repository to apply it
> feat: [Jaeger] Add maxTagValueLength for the feature request #2447

- configx/helpers.go
- configx/permission.go
- networkx/listener.go
- networkx/listener_test.go
This has been discussed here with @aeneasr :  https://github.com/ory/kratos/issues/1249
The goal of this patch is to move helpers functions that deal with unix socket from hydra to x, so it can be used by kratos
the changes.
works.
appropriate).
> refactor: move hydra unix sockets support helpers into ory/x

- configx/permission_test.go
Follow-up of https://github.com/ory/x/pull/328 ; I forgot to import some unit tests that were related to the stuff imported from ory/hydra
the changes.
works.
appropriate).
> test: import UnixPermission test from hydra

- jsonschemax/keys.go
- jsonschemax/keys_test.go
Fixes https://github.com/ory/hydra/issues/2518
the changes.
works.
appropriate).
> fix: Follow $ref in array items

- decoderx/http_test.go
- popx/migrator.go
- popx/transaction_test.go
the changes.
works.
appropriate).
> fix(popx): make migrator crdb resilient

- sqlcon/connector.go
- sqlcon/connector_test.go
- sqlcon/parse_opts.go
- sqlcon/parse_opts_test.go
This pull request is linked to ory/keto#523
This PR add a new sql database flag `max_idle_conn_time` to allow configration of https://golang.org/pkg/database/sql/#DB.SetConnMaxIdleTime
the changes.
works.
appropriate).
Note that this PR is breaking changes
> feat: parse max_idle_conn_time

- configx/options.go
the changes.
works.
appropriate).
> fix(watcherx): do not print config content

- sqlcon/dockertest/test_helper.go
Running `dockertest.KillAllTestDatabases` more than once results in a panic
```
panic: : No such container: 9bb7ffa7d4e07b7b3df91811baa3984698cfb2b5c90056a7b20de43e4e843ff1
```
because it was already killed in a previous run, but is still in the global slice.
> fix(dockertest): reset global resources after killing them

- fsx/merge.go
- fsx/merge_test.go
- networkx/manager.go
- popx/migration_box.go
This adds a small utility `fs.FS` that implements a merged file system. Further, the types in `popx.Migrator` are updated so that any `fs.FS` can be used. This allows us to do ` popx.NewMigrationBox(fsx.Merge(migrations, networkx.Migrations), popx.NewMigrator(p.Connection(ctx), p.d.Logger(), nil, 0))`, which in turn properly returns the status and also implements down migrations. Marked the `networkx.MigrateUp` func as deprecated, but maybe rather delete right away?
> feat: merged file system

- fsx/merge.go
- fsx/merge_test.go
The initial implementation was not `fs.Walk`able. This now implements all features and applies the full `fstest` testsuit. This should guarantee that the filesystem works.
Please note that we can't return `io.EOF` wrapped with `errors.WithStack` because of https://github.com/golang/go/issues/47062
> fix(fsx): make merged file system walkable and fully comply with "testing/fstest"

- configx/koanf_env.go
- configx/provider_test.go
- configx/stub/kratos/expected.json
- configx/stub/kratos/kratos.yaml
Currently it is not possible to override some values in the config if they are nested such as `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS`. It is still not possible to override some values that are nested inside `array` but this at least should allow to replace the whole array with some serialized JSON struct. It is not ideal but it should have some more options to deal with injecting secrets into Kratos et al. 
This is a follow up on https://github.com/ory/kratos/issues/1535
the changes.
works.
appropriate).
My initials investigation showed that even if I can generate nested keys …
> fix: allow to override some nested values in config.

- logrusx/helper.go
- logrusx/logrus_test.go
`l.WithError` should not panic but ignore `nil` errors, like other error handling functions (e.g. `errors.WithStack()`).
the changes.
works.
appropriate).
> fix(logrusx): do not panic on nil error

- configx/provider.go
- configx/provider_watch_test.go
the changes.
works.
appropriate).
> fix(configx): unlock provider before running watcher callbacks

- popx/migrator.go
- popx/migrator_test.go
- popx/test_migrator.go
This is a breaking change, but can easily be migrated by replacing
```diff
- popx.NewTestMigrator(t, c, "../migrations/sql", "./testdata", l)
+ popx.NewTestMigrator(t, c, os.DirFS("../migrations/sql"), os.DirFS("./testdata"), l)
```
> refactor(popx): test migrator should use fs.FS

- proxy/proxy.go
- proxy/proxy_full_test.go
- proxy/rewrites.go
- proxy/rewrites_test.go
BREAKING CHANGE: Before, the proxy host mapper would only receive the host. However, sometimes we need more than that to match the correct config. This patch addresses that.
```patch
- type HostMapper func(ctx context.Context, host string) (*HostConfig, error)
+ type HostMapper func(ctx context.Context, r *http.Request) (*HostConfig, error)
```
/cc @Benehiko @zepatrik 
the changes.
works.
appropriate).
> refactor(proxy): give host mapper the full request

- proxy/proxy.go
- proxy/proxy_full_test.go
- proxy/rewrites.go
- proxy/rewrites_test.go
The problem was that the body response replacement was not working since #426 when the upstream's and target's schemes did not match.
> fix(proxy): add target scheme for replacement

- httpx/resilient_client.go
- httpx/resilient_client_test.go
- tracing/http_client.go
- tracing/http_client_test.go
Add an option to trace Http call with resilient http client.
This originates from an (Work in progress) MR for kratos: https://github.com/ory/kratos/pull/2154
the changes.
works.
appropriate).
> feat: http client tracing

- sqlcon/dockertest/test_helper.go
- sqlcon/dockertest/test_helper_test.go
Test databases in docker images are now cleaned up automatically after the test finishes with `t.Cleanup()`.
Previously, databases started with the `dockertest.RunTest{DB}(*testing.T)` functions could not be cleaned up.
Closes Issue #460 
the changes.
works.
appropriate).
* The `Run{DB}() (string, error)` family of functions still do not return something to be cleaned up by, but adding a cleanup return function would change the API.
> feat(sqlcon): Cleanup test db docker images

- popx/migration_box.go
- popx/migration_box_gomigration_test.go
This is intended to help:
1. @hperl with https://github.com/ory/keto/pull/809 by allowing to run some go code between migrations
2. @grantzvolsky with NID in Hydra by allowing to generate the NID before migrating the tables over
> feat(popx): allow running custom go migrations

- proxy/proxy.go
- proxy/proxy_full_test.go
- proxy/rewrites.go
I have come across an issue while working on SPA integration using the [Ory Cli](https://github.com/ory/cli).
When running a development server when working on SPAs the browser opens a websocket connection to the development server for debugging purposes. I noticed that the Ory Cli was dropping the connection with the error:
```
internal error: 101 switching protocols response with non-writable body
```
After further investigation, it seemed that we were returning an `io.NopCloser` and replacing the `response.Body` entirely, which means any modification done internally by the `httputil.ReverseProxy` would be overwritten.
This change allows us to use the websocket response instead with its internal modifications with our modified body. …
> feat: websocket support

- logrusx/helper.go
- logrusx/logrus_test.go
This change ensures that URL query string is not written to logs when `Logf` family of functions is used and `leakSensitive` option is disabled.
URL query can contain sensitive data, e.g. API keys.
the changes.
works.
appropriate).
> feat: support 'leak_sensitive_values' in URL params

- configx/stub/from-files/config.schema.json
- configx/stub/hydra/config.schema.json
- configx/stub/kratos/config.schema.json
- configx/stub/multi/config.schema.json
- logrusx/config.schema.json
- logrusx/helper.go
- logrusx/logrus.go
- logrusx/logrus_test.go
- stringsx/default.go
- stringsx/default_test.go
This pull request introduces feature to configure sensitive log value redaction text. Current redaction text "**Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true".**" is too long and takes considerable amount of log space. 
the changes.
works.
appropriate).
> feat: make sensitive log value redaction text configurable

- cmdx/printing.go
- jsonx/get.go
- jsonx/get_test.go
As discussed previously with @Benehiko 
These testhelpers can be used to ensure that keys are always up-to-date in tests.
> feat(jsonx): add test helpers that ensure keys we retrieve exist on the type

- flagx/flagx.go
- flagx/flagx_test.go
Added `MustGetStringToStringMap()` to `github.com/ory/x/flagx` to enable use of key/val lookups from Cobra commands.
This will allow for example, updating the Hydra CLI to pass metadata as flags:
```
hydra clients create --metadata foo=bar,key=val
```
```go
map[string]string{
"foo": "bar",
"key": "val",
}
```
If this makes sense I will open a separate issue and PR on Hydra to add the appropriate changes to make use of this function there.
the changes.
works.
appropriate).
> Added string to string map lookup to flagx

- cloudx/cmd_update_identity_config_test.go
- cloudx/cmd_update_project_test.go
- configx/koanf_schema_defaults_test.go
- jsonschemax/keys_test.go
- jsonx/embed_test.go
- snapshotx/.snapshots/TestDeleteMatches-file=1.json-fn.json
- snapshotx/fixtures/1.json
- snapshotx/fixtures/2.json
- snapshotx/fixtures/3.json
- snapshotx/snapshot.go
- snapshotx/snapshot_test.go
Currently you can either ignore all matching OR exact keys. With this PR we have the ability to use both options at the same time.
Main use case: ignore all `created_at` timestamps and only ignore the root `id`.
> feat: improve usability of `snapshotx`

- healthx/handler.go
- healthx/handler_test.go
**BREAKING CHANGES**: changes the API definitions of the following 
`healthx/Alive, healthx/Ready, healthx/Version, healthx/SetHealthRoutes,healthx/SetVersionRoutes`
will add support for passing a middleware to the register
function, also changes the actual handlers to return http.handlers
instead
lays the base set of changes for https://github.com/ory/hydra/pull/3114
the changes.
works.(modified existing tests)
appropriate).
> refactor: API changes for healthx for middleware

- Makefile
- clidoc/generate.go
- clidoc/md_docs.go
- cmdx/http.go
- cmdx/printing.go
- configx/koanf_file.go
- corsx/middleware.go
- corsx/middleware_test.go
- fetcher/fetcher.go
- jsonnetx/format.go
- jsonnetx/lint.go
- migratest/run.go
- osx/file.go
- pkgerx/file.go
- popx/migrator.go
- sqlcon/dockertest/test_helper.go
- tracing/http_client.go
- watcherx/directory.go
- watcherx/directory_test.go
- watcherx/file.go
- watcherx/file_test.go
- watcherx/websocket_test.go
@Benehiko PTAL https://github.com/ory/x/commit/e294636fb31bbe24969ffc42b5e17c3807b52783
We should use this CORS handler for backoffice, kratos and remove the CORS handling from the bo proxy so that oryapis.com can also have CORS
> Add http client cmdx helper

- popx/migration_box.go
Fix resource leak in `findMigrations`.
> fix(popx): close file to fix resource leak

- openapix/doc.go
- openapix/jsonpatch.go
- openapix/pagination.go
> feat(openapix): add common openapi definitions

- jsonx/patch.go
- jsonx/patch_test.go
json-patch panics when the operator is "test" and the value
is empty. Until this is fixed upstream, we disallow "test".
> fix: remove support for JSONPatch 'test'

- otelx/otlp.go
- tracing/tracer.go
The middleware already attempts to extract a parent trace from the HTTP
request. However, that does nothing unless a global OTEL propagator is
configured. This patch adds that configuration.
An alternative is to configure the propagator only for the otel Bridge:
bridge := otelOpentracing.NewBridgeTracer()
bridge.SetTextMapPropagator(...)
But considering that the bridge only exists due to the use of a
deprecated package it seems more appropriate to configure the global
propagator in the non-deprecated package.
The tracing middleware calls `remoteContext, _ := opentracing.GlobalTracer().Extract(...)` to get the parent span, if any:
https://github.com/ory/x/blob/df7f8ab7bc01df3c1584b2bd9d2c443197ea1157/tracing/middleware.go#L23-L27
`opentracing.GlobalTracer()` returns the bridge set up …
> fix(tracing): enable trace propagation for OTEL

- go.mod
- go.sum
The version of https://github.com/mattn/go-sqlite3 (`v2.0.3`) used in this repo has been retracted. The latest version is actually `v1.14.15`.
This is causing issues for me when attempting to use `ory/fosite` directly.
```sh
$ go get github.com/mattn/go-sqlite3@latest
go: downgraded github.com/mattn/go-sqlite3 v2.0.3+incompatible => v1.14.15
go: downgraded github.com/ory/fosite v0.42.3-0.20220813141926-575ae6d63ed6 => v0.35.1
go: downgraded github.com/ory/x v0.0.214 => v0.0.109
```
> fix: Downgrade github.com/mattn/go-sqlite3 from retracted version

- popx/migrator.go
Just took two days to figure out...
What was happening:
1. [huge migration](https://github.com/ory/keto/blob/d007bae4ce7b507f17f5c907bf90f858cfcd2950/internal/persistence/sql/migrations/uuidmapping/uuid_mapping_migrator.go) with ~100.000 rows against CRDB
2. no error during execution, but the commit errored with `restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORTED_RECORD_FOUND)` because of low resources on my local laptop
3. therefore `err` was `nil`, but `dberr` was not
4. finally, `errors.Wrapf` was called with a `nil` error, and therefore silently droppend the non-nil `dberr`
> fix: migrator error handling

- httpx/client_info.go
- httpx/client_info_test.go
- httpx/private_ip_validator.go
- stringsx/ptr.go
- stringsx/ptr_test.go
- Introducing helper utility to extract the first IP address not on an exclusion list
- Adding helper utility for string pointers
Resolves (partially) https://github.com/ory-corp/cloud/issues/3011
> feat: helper to extract ip address that isn't on an exclusion list

- reqlog/middleware_test.go
This fixes a flaky assertion that depends on the process being resumed from sleep in less than 16 ms (nap duration - 10ms + 6ms arbitrary number). The other assertion which tests that the process sleeps for a minimum of the the nap duration defined is sufficient.
> test: remove assertion for time elapsed being less than magic number

- configx/provider.go
- otelx/config.schema.json
FYI @icyphox, this was also needed to get zipkin working :wink:
> fix: `(*configx.Provider).TracingConfig` should parse all providers configs

- tlsx/cert.go
- tlsx/cert_test.go
```
Adds the ability to automatically reload TLS certificates read from the filesystem in the background with a configurable interval.
```
Implements (part of) https://github.com/ory/hydra/issues/2850
introduces a new feature: _this is an initial swing at the problem: let me know if you think the design is wrong._
the changes.
works.
appropriate).
The obvious alternative to periodically reloading every _x_ seconds is to use a file watching API, say https://github.com/fsnotify/fsnotify. The problem with that (beside introducing a new dependency) is that this functionality doesn't …
> Automatic TLS certificate reload

- pagination/pagepagination/pagination.go
- pagination/pagepagination/pagination_test.go
Fix pagination response headers unnecessarily including the "prev" link when the total count of items exactly matched the `per_page` pagination value.
I haven't created an issue for this bug, but I did briefly mention it in another PR here: https://github.com/ory/kratos/pull/2763#issuecomment-1261737747
**The issue:** Pagination response headers were including the "prev" link with the `page` query param set to `-1` when the total count of items exactly matched the page size. This fix simply omits the "prev" link in such a cases, because the single page already contains all items.
**How to reproduce:**
1. Get the total count for a paginated endpoint (total count should be less than the max allowed page size): 
```console
$ curl --verbose --location --request GET …
```
> fix(pagination): fixed prev link with negative page value

- cmdx/http.go
Fix an issue that causes the Hydra CLI to crash. Potentially affects any CLI that depends on `ory/x/cmdx`.
Fixes https://github.com/ory/hydra/issues/3370
Ideally there should be unit tests covering `http.go` but at the moment I don't have time to add them in this PR.
> fix: assignment to entry in nil map error when handling HTTP header CLI arguments

- pagination/keysetpagination/header.go
- pagination/keysetpagination/header_test.go
- pagination/keysetpagination/page_token.go
- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
> feat: add additional column ordering to keysetpagination

- cmdx/printing.go
- cmdx/printing_test.go
- go.mod
> feat: add --output=jsonpointer

- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
Fixes the operator precedence in `keysetpagination` queries. 
Before this change the queries that resulted from the `keysetpagination` looked like this:
```sql
SELECT
*
FROM
courier_messages
WHERE
nid = $1
AND "created_at" < $2
OR (
"created_at" = $2
AND "id" > $3
)
ORDER BY
"created_at" DESC,
"id" ASC
LIMIT
11
```
This could lead to the `nid = $1` clause being ignored.
This PR fixes that by turning the above statement into:
```sql
SELECT
*
FROM
courier_messages
WHERE
nid = $1
AND (
"created_at" < $2
OR (
"created_at" = $2
AND "id" > $3
)
)
ORDER BY
"created_at" DESC,
"id" ASC
LIMIT
11
```
> fix: operator precendence in keysetpagination

- configx/options.go
- configx/provider.go
- otelx/withspan_test.go
- watcherx/file.go
I've disassociated the context used for tracing during config reloads from what's being set in `configx.WithContext`.
More generally, I feel we store too much stuff in contexts and have too much magic of injecting configuration. We also store contexts inside structures occasionally, which is an anti-pattern. I'd like to clean this up more after this PR.
> fix: spurious spans from config reloader

- .github/workflows/test.yml
- watcherx/changefeed.go
- watcherx/changefeed_test.go
- watcherx/file.go
- watcherx/file_test.go
- watcherx/testmain_test.go
- watcherx/websocket_test.go
This fixes another goroutine leak, manifesting as this test flake: https://github.com/ory/x/actions/runs/4231863448/jobs/7350899773#step:12:489
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 108 in state select, with github.com/fsnotify/fsnotify.(*Watcher).sendEvent on top of the stack:
goroutine 108 [select]:
github.com/fsnotify/fsnotify.(*Watcher).sendEvent(...)
/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:156
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0009d1630)
/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:429 +0x705
created by github.com/fsnotify/fsnotify.NewWatcher
/home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:150 +0x1b0
Goroutine 109 in …
```
> fix(watcherx): go routine leak

- popx/transaction.go
- popx/transaction_test.go
This should allow us to monitor transaction contention in Grafana.
> feat: collect Prometheus metrics on automatic transaction retries (cockroachdb)

- healthx/handler.go
- healthx/handler_test.go
- healthx/openapi/patch.yaml
This is problematic during code generation in downstream projects ever since https://github.com/ory/herodot/pull/106. Since the handler never returns an error (a failing liveness check means you don't get a response at all), the simplest and most correct thing to do is to just not declare an error type at all.
> fix: health/alive handler never errors

- go.mod
- go.sum
- jsonx/patch.go
- jsonx/patch_test.go
This PR fixes https://github.com/ory/kratos/issues/3244, which fails to add a field to `metadata_public`/`metadata_admin` when nothing yet exists in that object / when the objects are null.
To achieve this we instruct json-patch to create the missing path.
I had to update to a different version of `json-patch` I hope it's fine 🥹
https://github.com/ory/kratos/issues/3244
https://ory-community.slack.com/archives/C012USDT5QQ/p1685968287885839
It's still TBD whether we should introduce the change globally or only enable the new behavior via a dedicated option.
I'm happy to work on changing the behavior by …
> fix(jsonx): enable PATCHing an object's field when the object does not exist yet

- decoderx/http.go
An oversight in https://github.com/ory/x/commit/c8bd35e3bcceec8001475a4b8ee44700aa6ba382#diff-596c1a0e52378833155314a336e270dcdec55f3c79bc0cc88f0204c8b49369feR552-R554 caused a breaking change. This restores the old behavior.
> fix(decoderx): allow unknown fields

- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
Because if the paginator is used on joined queries, there can be "ambiguous column name" errors.
> fix(pagination): add table name to fields in keyset pagination

- proxy/proxy.go
- proxy/rewrites_test.go
Ory Oathkeeper v0.44.4 uses the new `Rewrite` functionality in the Golang Proxy. This will strip `X-Fowarded-Proto` headers which messes with the TLS detection logic here.
To fix this, add an option which forces the TLS detection to always return HTTPS.
> feat: support override for originalScheme

- jsonx/patch.go
- proxy/proxy.go
- proxy/proxy_full_test.go
Adds a feature flag to revert regressions introduced by switching to proxy.Rewrite.
> feat(proxy): flag to keep forwarded headers

- clidoc/generate_test.go
- clidoc/md_docs.go
- clidoc/testdata/root-child1.md
- cmdx/usage.go
This results in the same results as we already have in the help templates. How did we not notice it until now??
> feat(clidoc): enable templating for command fields

- configx/provider.go
- otelx/config.go
- otelx/config.schema.json
- otelx/otlp.go
This PR adds 'Authorization` header to all OTEL requests
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security vulnerability. 
> feat: add `Authorization` header to OTEL config (CORE-2291)

- configx/options.go
- configx/provider.go
- configx/provider_watch_test.go
- corsx/check_origin.go
- corsx/check_origin_test.go
- corsx/middleware.go
This makes it possible to allow hot-reloading e.g. the CORS origins, while the rest of the serve key is not hot-reloadable.
> feat(configx): allow exceptions in immutables

- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
see https://github.com/gobuffalo/pop/pull/829
> fix(pagination): quote function broken for mysql

- go.mod
- go.sum
- pagination/keysetpagination/parse_header.go
- pagination/keysetpagination/parse_header_test.go
> feat: add token pagination link header parser

- pagination/keysetpagination/header.go
- pagination/keysetpagination/header_test.go
fixes some issues in keyset pagination
> fix: link header in keyset pagination

- crdbx/staleness.go
- crdbx/staleness_test.go
> feat: add crdb consistency guarantees

- decoderx/http.go
This fixes 12 `err` variables in the `decoderx` package that are being dropped due to the use of `:=` in single-line `if x, err := func(y); err != nil` statements.
> fix: decoderx dropped errors

- httpx/resilient_client.go
- httpx/resilient_client_test.go
- httpx/ssrf.go
- jsonnetsecure/jsonnet_pool.go
* improve connection re-use
* add detailed trace events (DNS, TLS, etc)
Looks like this in Tempo: left is a newly established connection, right is a reused connection.
> feat: add http client option to disable IPv6

- healthx/doc.go
- healthx/openapi/patch.yaml
> fix: use schemas for health

- .github/workflows/format.yml
- .github/workflows/licenses.yml
- .github/workflows/test.yml
- go.mod
- httpx/external_latency.go
- httpx/ssrf.go
- proxy/proxy_full_test.go
- reqlog/external_latency.go
- reqlog/external_latency_test.go
- reqlog/middleware.go
This adds a middleware and utilities to measure external latency.
> feat: measure external latency

- httpx/client_info.go
- httpx/client_info_test.go
Adds `Cf-Connecting-IP` to the list of headers to check for real client IP. This header is set by Cloudflare to have the real client IP address. 
https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip
Since we are already relying on cloudflare headers for device location and how ubiquitous Cloudflare has become it's a good idea to have support for it.
We cannot rely on `X-forwarded-for` when behind Cloudflare as well, since the order of the IPs listed by Cloudflare is not the order this library checks. 
> feat(httpx): use cf-connecting-ip header for client IP

- assertx/assertx.go
- cmdx/helper.go
- cmdx/printing.go
- cmdx/printing_test.go
- fetcher/fetcher.go
- jsonschemax/keys.go
- logrusx/logrus.go
- stringslice/filter.go
- stringslice/has.go
- stringslice/merge.go
- stringslice/reverse.go
- stringslice/unique.go
- stringsx/default.go
- stringsx/ptr.go
- stringsx/switch_case.go
A couple of helpers got obsolete by new stdlib functions, mainly generic slices. Changed those to use the stdlib internally, and added deprecation warnings.
Also, improved a few minor APIs, everything backwards compatible.
> chore: small improvements and deprecations

- jsonnetsecure/jsonnet.go
- jsonnetsecure/jsonnet_pool.go
- jsonnetsecure/jsonnet_processvm.go
> fix(jsonnet): add configurable timeout

- popx/migrator.go
This reverts a part of #762 where it was incorrectly removed.
> fix: migrator should skip down migrations that were not yet applied

- .github/workflows/test.yml
- .golangci.yml
- Makefile
- cmdx/http.go
- httpx/gzip_server.go
- jsonnetsecure/jsonnet.go
- jsonnetsecure/jsonnet_pool.go
- jsonnetsecure/jsonnet_processvm.go
- jsonnetsecure/provider.go
Reverts #798 and #799 
The fixed 1 second timeout now only applies to the Jsonnet evaluation step,
but not the the spawning of the process which can occasionally take longer.
Additionally, we now warm the pool asynchronously on construction.
> fix: occasional jsonnet timeouts

- httpx/resilient_client.go
- httpx/ssrf.go
Should fix a memory leak introduced by a otel SDK bump.
> fix: reuse OpenTelemetry-wrapped http.Transport

- otelx/withspan.go
Without this change, a non-herodot error does not add any details to the trace, but only sets the status to error. It is super hard to debug then.
> fix(otelx): always set error in `End`

- otelx/semconv/events.go
Follow up of #810 as we actually should distinguish the API key type.
> fix(otelx): distinguish workspace and project API keys

- decoderx/http.go
> chore: add body to error if we are unable to decode it

- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
We probably never want an unbound pagination. The specific implementation can still override the max page size.
> fix(pagination): always enforce max size is set

- hasherx/hash_comparator.go
- mapx/type_assert.go
The implicit type conversions of untyped ints did overflow on 32-bit int sized architectures.
```
failed to build for linux_arm_6: exit status 1: # github.com/ory/x/hasherx
Error: /go/pkg/mod/github.com/ory/x@v0.0.665/hasherx/hash_comparator.go:168:18: math.MaxUint32 (untyped int constant 4294967295) overflows int
Error: /go/pkg/mod/github.com/ory/x@v0.0.665/hasherx/hash_comparator.go:178:17: math.MaxUint32 (untyped int constant 4294967295) overflows int
Error: /go/pkg/mod/github.com/ory/x@v0.0.665/hasherx/hash_comparator.go:211:18: math.MaxUint32 (untyped int constant 4294967295) overflows int
Error: /go/pkg/mod/github.com/ory/x@v0.0.665/hasherx/hash_comparator.go:221:17: math.MaxUint32 (untyped int constant 4294967295) overflows int
Error: …
```
> fix: build on 32-bit architectures

- configx/provider.go
- configx/provider_watch_test.go
This fixes an issue where we were leaking many goroutines especially during tests, even though there are no files to watch.
Those goroutines are cancelable via the context passed in, but we rarely do that in test code. And if we do, we spawn literally thousands of goroutines before doing one big cancel at the end.
IMO, this whole watching code should either go away or be refactored so it is more obvious that it spawns background goroutines.
> fix: don't leak goroutines if there are no files to watch

- popx/cmd.go
> docs: improve cli messages

- sqlcon/dockertest/test_helper.go
Causes Keto `go test -race` to fail occasionally.
> fix: data race in dockertest

- .github/workflows/licenses.yml
- go.mod
- go.sum
- go_mod_indirect_pins.go
> fix: remove unused dep

- jsonx/patch.go
- jsonx/patch_test.go
> feat: add glob deny paths to ApplyJSONPatch

- otelx/withspan.go
- otelx/withspan_test.go
This is mostly for better Datadog compatibility. Datadog does not natively implement OpenTelemetry and its conventions, so there is a certain amount of impedance mismatching. Datadog also does not document properly where certain error info needs to be stored within a span to show up correctly in their UI. This is my best guess from the docs scattered around their website.
We might have to iterate on this.
> feat: add more error info to traces

- cachex/ristretto.go
- configx/provider_watch_test.go
> feat: collect ristretto cache metrics helper

- randx/sequence.go
The visually ambiguous characters were suggested by ChatGPT.
https://chatgpt.com/share/67979762-832c-800e-8ccf-8a0c1d3b0ce0
> feat: add AlphaNumNoAmbiguous rune set to randx

- popx/migrator.go
Information about the number of applied migrations is very useful in case someone needs to perform a revert (down migration). It should be exposed in the logs when the default log level is set.
> chore(popx): change log level for migrator logs

- otelx/withspan.go
- otelx/withspan_test.go
Added some documentation links too.
> feat: populate "errors.stack" span attribute when panicking through otelx.End()

- logrusx/helper.go
- prometheusx/handler.go
- prometheusx/handler_test.go
- prometheusx/metrics.go
- prometheusx/metrics_test.go
- prometheusx/middleware.go
- prometheusx/middleware_test.go
- tlsx/termination.go
- tlsx/termination_test.go
This PR is moving code from ory/hydra to ory/x:
- https://github.com/ory/hydra/blob/d389fd0269f93c8b7c787f1b3683ae4c6e9e1909/x/tls_termination.go
- https://github.com/ory/hydra/blob/d389fd0269f93c8b7c787f1b3683ae4c6e9e1909/x/tls_termination_test.go
> feat(tlsx): add validation for TLS termination

- pagination/keysetpagination/paginator.go
- pagination/keysetpagination/paginator_test.go
This change ensures that we can construct a paginator from `ToOptions` which results in the same paginator again. Previously we would apply some defaults incorrectly.
> fix(pagination): make keyset paginator `ToOptions` idempotent
